/*
 * ProjectFrame.java
 *
 * Created on June 10, 2007, 9:18 PM
 */

package com.davidhagar.selectiveimagery.ui;

import java.awt.*;

import javax.swing.JOptionPane;

import com.davidhagar.selectiveimagery.model.Generation;
import com.davidhagar.selectiveimagery.model.LayeredImage;
import com.davidhagar.selectiveimagery.model.Project;

/**
 * 
 * @author David Hagar
 */
public class ProjectFrame extends javax.swing.JFrame
{


	Project project;

	int parentViewIndex = -1;


	public ProjectFrame(Project project)
	{
		this.project = project;

		initComponents();

        setFrameSize();

		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				refreshParentView();
				refreshCurrentGenerationView();
			}
		});
	}

    private void setFrameSize() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        frameSize.height = screenSize.height - 50;
        frameSize.width = screenSize.width - 200;
        this.setSize(frameSize);

        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
    }


    private void refreshCurrentGenerationView()
	{
		currentGenerationPanel.removeAll();

		if (project.generationList.isEmpty())
			return;

		Generation g = project.generationList
				.get(project.generationList.size() - 1);

		int w = currentGenerationPanel.getWidth();
		int h = currentGenerationPanel.getHeight();
		Dimension d = getColumnConfiguration(w, h, g.imageList.size());

		GridLayout gl = (GridLayout) currentGenerationPanel.getLayout();
		gl.setColumns(d.width);
		gl.setRows(d.height);

		//System.out.println(d);

		for (LayeredImage li : g.imageList)
		{
			currentGenerationPanel.add(new ImagePanel(li));
		}

		currentGenerationScrollPane.revalidate();

	}


	private void refreshParentView()
	{
		// TODO Auto-generated method stub

	}


	/** Creates new form ProjectFrame */
	public ProjectFrame()
	{
		initComponents();
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents()
	{
		jPanel1 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		parentScrollPanel = new javax.swing.JScrollPane();
		jPanel6 = new javax.swing.JPanel();
		parentGenerationPanel = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		currentGenerationScrollPane = new javax.swing.JScrollPane();
		currentGenerationPanel = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		jPanel8 = new javax.swing.JPanel();
		generateNextButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		jPanel1.setLayout(new java.awt.BorderLayout());

		jPanel4.setLayout(new java.awt.BorderLayout());

		jPanel6.setLayout(new java.awt.BorderLayout());

		parentGenerationPanel.setLayout(new javax.swing.BoxLayout(
				parentGenerationPanel, javax.swing.BoxLayout.X_AXIS));

		jPanel6.add(parentGenerationPanel, java.awt.BorderLayout.WEST);

		parentScrollPanel.setViewportView(jPanel6);

		jPanel4.add(parentScrollPanel, java.awt.BorderLayout.CENTER);

		jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

		jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5,
				javax.swing.BoxLayout.Y_AXIS));

		jButton1.setText("Back");
		jPanel5.add(jButton1);

		jButton2.setText("Next");
		jPanel5.add(jButton2);

		jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

		getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

		jPanel2.setLayout(new java.awt.BorderLayout());

		jPanel3.setLayout(new java.awt.BorderLayout());

		currentGenerationPanel.setLayout(new java.awt.GridLayout(10, 10));

		currentGenerationScrollPane.setViewportView(currentGenerationPanel);

		jPanel3.add(currentGenerationScrollPane, java.awt.BorderLayout.CENTER);

		jPanel7.setLayout(new java.awt.BorderLayout());

		jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8,
				javax.swing.BoxLayout.X_AXIS));

		generateNextButton.setText("Generate Next");
		generateNextButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				generateNextButtonActionPerformed(evt);
			}
		});

		jPanel8.add(generateNextButton);

		jPanel7.add(jPanel8, java.awt.BorderLayout.EAST);

		jPanel3.add(jPanel7, java.awt.BorderLayout.NORTH);

		jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

		getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 1000) / 2, (screenSize.height - 800) / 2, 1000,
				800);
	}// </editor-fold>//GEN-END:initComponents


	private void generateNextButtonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_generateNextButtonActionPerformed

		if (project.getLastGeneration().getSelected().size() < 2)
		{
			JOptionPane.showMessageDialog(this, "Must select at least two images.");
			return;
		}

		try
		{
			project.makeNextGeneration();
		}
		catch (Exception e)
		{
			JOptionPane.showMessageDialog(this, "Error:" + e.getMessage());
			e.printStackTrace();
		}

		refreshCurrentGenerationView();

	}// GEN-LAST:event_generateNextButtonActionPerformed


	private Dimension getColumnConfiguration(int width, int height, int n)
	{

		float winAspect = ((float) height) / width;
		int nx = 1;
		int ny = 1;

		while (nx * ny <= n)
		{
			float aspect = ((float) ny) / nx;
			if (aspect >= winAspect)
				nx++;
			else
				ny++;
		}

		float aspect = ((float) ny) / nx;

		if (aspect > winAspect)
			nx++;

		// float cellWidth = (float) (width / nx);

		return new Dimension(nx, ny);
	}


	/**
	 * @param args
	 *          the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new ProjectFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel currentGenerationPanel;
	private javax.swing.JScrollPane currentGenerationScrollPane;
	private javax.swing.JButton generateNextButton;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel parentGenerationPanel;
	private javax.swing.JScrollPane parentScrollPanel;
	// End of variables declaration//GEN-END:variables

}
